### ISSUE TITLE
How can I create a undirected graph?

### ISSUE THREAD

**Issue by FranciscaGeorgue** [asiftasleem/angular-2-cytoscape#1]
I could integrate your example into my project, but I do not know how I could create an undirected graph

**Comment by TianrenWang** [comment]
In the ng-cyto.component.ts there are some parameters about arrowed edges in the edges style. Remove or modify them to get rid of the undirectedness.

**Comment by asiftasleem** [comment]
Set the layout directed property to false:
        this.layout = this.layout || {
                name: 'grid',
                **directed: false,**
                padding: 0
            };

And change the following cytoscape css property to none:
'target-arrow-shape': '**none**',
