### ISSUE TITLE
Importing layout extensions

### ISSUE THREAD

**Issue by TianrenWang** [asiftasleem/angular-2-cytoscape#2]
I opened an issue here https://github.com/cytoscape/cytoscape.js-klay/issues/13 about trying to import layout extensions into your project. I noticed that you successfully imported dagre, how would you do it for a different extension like klay? I installed the klay package and imported the necessary scripts in angular.json file, but I still get error saying that some layout object in the package script is undefined.

**Comment by gabrieldelaparra** [comment]
Hi @TianrenWang, Did you realized how?

**Comment by leuch3rd** [comment]
I'm actually having the same issue @gabrieldelaparra with a different layout package
I'm importing in my angular.json file but am getting the same undefined error.  Do you have any advice on how you imported the layout?

**Comment by gabrieldelaparra** [comment]
Hi, I managed to solve it. I will post a snipped later on today.

Cheers,

**Comment by TianrenWang** [comment]
I never solved the issue but I ended up using fcose layout and that one doesn't have the same issue.

**Comment by gabrieldelaparra** [comment]
Hi @TianrenWang @leuch3rd,

In my case, I was trying to get [cytoscape.js-cose-bilkent](https://github.com/cytoscape/cytoscape.js-cose-bilkent) to run.

From the `cytoscape.js-cose-bilkent` project description, for plain JS, the following scripts are required:
``` html
<script src="https://unpkg.com/layout-base/layout-base.js"></script>
<script src="https://unpkg.com/cose-base/cose-base.js"></script>
<script src="cytoscape-cose-bilkent.js"></script>
```
We will need this now.
1. Clone `angular-2-cytoscape`
2. `cd` to the dir and run `npm install`
3. `npm install cytoscape-cose-bilkent`
4. On the `angular.json`, add the following lines:
```
"scripts": [
              "node_modules/cytoscape/dist/cytoscape.min.js",
              "node_modules/layout-base/layout-base.js",
              "node_modules/cose-base/cose-base.js",
              "node_modules/cytoscape-cose-bilkent/cytoscape-cose-bilkent.js",
              "node_modules/dagre/dist/dagre.min.js",
              "node_modules/cytoscape-dagre/cytoscape-dagre.js"],
```
5. Change the layout on your `graph-component.ts` to `name: 'cose-bilkent'`
6. Voila. run `ng serve` to see the layout being applied.

I think that the same should be valid for other layouts.

Cheers,

**Comment by gabrieldelaparra** [comment]
For `klay` I did the same:
3. `npm install cytoscape-klay`

and on `angular.json`:
```
"node_modules/klayjs/klay.js",
"node_modules/cytoscape-klay/cytoscape-klay.js",
```
It worked as well.

**Comment by asiftasleem** [comment]
Thank you @gabrieldelaparra.

**Comment by octalpixel** [comment]
> I never solved the issue but I ended up using fcose layout and that one doesn't have the same issue.

@TianrenWang can you help me with fcose , I couldnt get it  to work
